### ISSUE TITLE
Linking CXX executable unit_test -> undefined reference error

### ISSUE THREAD

**Issue by ramtej** [EOSIO/eosio.contracts#37]
Hi guys, 

I;m getting the following issue:

[ 82%] Linking CXX executable eosio.system.wasm
[ 82%] Built target eosio.system.wasm
[100%] Linking CXX executable unit_test
CMakeFiles/unit_test.dir/eosio.msig_tests.cpp.o: In function `eosio_msig_tests::propose_approve_execute::test_method()':
**/home/jj/tmp/eosio.contracts/tests/eosio.msig_tests.cpp:(.text+0x1790): undefined reference to `eosio::testing::base_tester::abi_serializer_max_time'**
CMakeFiles/unit_test.dir/eosio.msig_tests.cpp.o: In function `eosio_msig_tests::propose_approve_unapprove::test_method()':
/home/jj/tmp/eosio.contracts/tests/eosio.msig_tests.cpp:(.text+0x5210): undefined reference to `eosio::testing::base_tester::abi_serializer_max_time'
CMakeFiles/unit_test.dir/eosio.msig_tests.cpp.o: In function `eosio_msig_tests::propose_approve_by_two::test_method()':
/home/jj/tmp/eosio.contracts/tests/eosio.msig_tests.cpp:(.text+0x861e): undefined reference to `eosio::testing::base_tester::abi_serializer_max_time'
CMakeFiles/unit_test.dir/eosio.msig_tests.cpp.o: In function `eosio_msig_tests::propose_with_wrong_requested_auth::test_method()':
/home/jj/tmp/eosio.contracts/tests/eosio.msig_tests.cpp:(.text+0xc42e): undefined reference to `eosio::testing::base_tester::abi_serializer_max_time'
CMakeFiles/unit_test.dir/eosio.msig_tests.cpp.o: In function `eosio_msig_tests::big_transaction::test_method()':
/home/jj/tmp/eosio.contracts/tests/eosio.msig_tests.cpp:(.text+0xf7d7): undefined reference to `eosio::testing::base_tester::abi_serializer_max_time'
CMakeFiles/unit_test.dir/eosio.msig_tests.cpp.o:/home/jj/tmp/eosio.contracts/tests/eosio.msig_tests.cpp:(.text+0x157c2): more undefined references to `eosio::testing::base_tester::abi_serializer_max_time' follow
CMakeFiles/unit_test.dir/eosio.msig_tests.cpp.o: In function `eosio::testing::contracts::util::exchange_wasm()':
/home/jj/tmp/eosio.contracts/tests/eosio.msig_tests.cpp:(.text._ZN5eosio7testing9contracts4util13exchange_wasmEv[_ZN5eosio7testing9contracts4util13exchange_wasmEv]+0x1a): undefined reference to `eosio::testing::read_wasm(char const*)'

Environment: Ubuntu 16.04

Regards, 
jj

**Comment by ramtej** [comment]
Update: Works on Ubuntu 18.04

**Comment by ramtej** [comment]
Update II: It was required to delete manually

/usr/local/lib/**libeosio_testing.a**

**Comment by larryk85** [comment]
There is a script in [eos](https://github.com/eosio/eos) under the ```scripts``` folder named ```clean_old_install.sh``` this will remove the old install and eliminate linkage and inclusion conflicts.
