### ISSUE TITLE
unable to compile in MacOS

### ISSUE THREAD

**Issue by kesar** [EOSIO/eosio.contracts#42]
macosx

sh build.sh

getting:

[ 35%] Built target eosio.token.wasm
[ 47%] Performing build step for 'contracts_unit_tests'
[ 52%] Built target eosio.msig.wasm
[ 52%] Built target eosio.sudo.wasm
[ 52%] Built target eosio.system.wasm
[ 16%] Linking CXX executable unit_test
Undefined symbols for architecture x86_64:
  "fc::to_variant(fc::crypto::public_key const&, fc::variant&)", referenced from:

...

      eosio_system::eosio_system_tester::setup_producer_accounts(std::__1::vector<eosio::chain::name, std::__1::allocator<eosio::chain::name> > const&) in eosio.system_tests.cpp.o
      ...
ld: symbol(s) not found for architecture x86_64
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [unit_test] Error 1
make[4]: *** [CMakeFiles/unit_test.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [contracts_unit_tests-prefix/src/contracts_unit_tests-stamp/contracts_unit_tests-build] Error 2
make[1]: *** [CMakeFiles/contracts_unit_tests.dir/all] Error 2
make: *** [all] Error 2

**Comment by kesar** [comment]
issue not happens if i comment the unit tests part in CMakeList.txt

**Comment by jgiszczak** [comment]
Probably https://github.com/EOSIO/eos/issues/5039
Boost 1.67 is required.

**Comment by kesar** [comment]
tried this, but it didnt work in eos folder (I have installed 1.67):

sudo ./scripts/clean_old_install.sh
./eosio_build.sh
sudo make install
then export the above mention PATH/LD_LIBRARY_PATH

LD_LIBRARY_PATH=/usr/local/eosio/lib:/Users/kesar/.gvm/pkgsets/go1.9.2/global/overlay/lib:

**Comment by dabdevelop** [comment]
Install the eos sdk here:

https://github.com/EOSIO/eosio.wasmsdk

**Comment by kesar** [comment]
i did it too

**Comment by abhi3700** [comment]
Same here.
Still the eosio-cpp build fails.
Error: due to boost library inclusion.

**Comment by kesar** [comment]
stilll happening after 1.2.0 EOS

Undefined symbols for architecture x86_64

any idea? seems to work fine in my ubuntu virtual machine.

**Comment by wuyahuang** [comment]
Same here.

**Comment by ramtej** [comment]
+1 same issue..

**Comment by kesar** [comment]
yup, still happening :/

**Comment by gleehokie** [comment]
@kesar this is working for 100s of others so there must (!) be something different on your machine.  Please start from scratch (git clone) and let us know what happens.  Be sure to use all the newest releases.  Thanks.
